Repository dnd-side-project/dnd-9th-9-frontend, pull requests merged in 2023-09, with the labels that each got.

#81 🔨 refactor: theme type 선언 수정
  src/assets/styles/emotion.d.ts
  src/assets/styles/theme.ts
  src/components/Alarm/AlarmItem.tsx
  src/components/Button/NavigateButton.tsx
  src/components/Tag/Tag.tsx
  src/components/Text/Text.tsx
Labels: ♻️ refactor

#76 ✨ feat: 매칭 목록, 필터 화면 작업 및 api 연동
  src/assets/svg/index.ts
  src/components/Count/Count.tsx
  src/components/List/ListItem.tsx
  src/components/Searching/Searching.tsx
  src/features/match/components/MatchFilter/MatchFieldTypeFilterRadio.tsx
  src/features/match/components/MatchFilter/MatchFilterItem.tsx
  src/features/match/components/MatchFilter/MatchFilterSelect.tsx
  src/features/match/components/MatchFilter/index.ts
  src/features/match/components/MatchList/MatchingList.tsx
  src/features/match/components/MatchList/index.ts
  src/features/match/components/MatchRadio/MatchTypeRadio.tsx
  src/features/match/components/MatchRadio/index.ts
  src/features/match/components/index.ts
  src/features/match/hooks/field/index.ts
  src/features/match/hooks/field/keys.ts
  src/features/match/hooks/field/useGetFieldDetail.ts
  src/features/match/hooks/field/useGetFieldList.ts
  src/features/match/hooks/field/useGetInfiniteFieldList.ts
  src/features/match/types/field.ts
  src/navigators/MatchNavigator.tsx
  src/screens/match/MatchScreen.tsx
  src/screens/match/detail/MatchDetailProfileScreen.tsx
  src/screens/match/list/MatchFilterScreen.tsx
  src/screens/match/list/MatchListScreen.tsx
Labels: ♻️ refactor, 🔥 high priority, 💫 feature

#75 ✨ feat: 운동 메모 작성 페이지 구현 및 api 연동
  src/assets/svg/index.ts
  src/components/CheckBox/CheckBox.tsx
  src/features/match/components/MatchDetailMatching/MatchApplyListItem.tsx
  src/features/record/components/CreateWorkoutInformation/ExpectedBurnedCaloriesSection.tsx
  src/features/record/components/CreateWorkoutInformation/Modal/WorkoutActivityTimeModal.tsx
  src/features/record/components/CreateWorkoutInformation/index.ts
  src/features/record/components/CreateWorkoutMemo/ImagePreview.tsx
  src/features/record/components/CreateWorkoutMemo/InformationSection.tsx
  src/features/record/components/CreateWorkoutMemo/ReadOnlyTextfield.tsx
  src/features/record/components/CreateWorkoutMemo/index.ts
  src/features/record/hooks/exercise/index.ts
  src/features/record/hooks/exercise/keys.ts
  src/features/record/hooks/exercise/useGetExerciseCalorie.ts
  src/features/record/hooks/exercise/useGetExpectedBurnedCalorie.ts
  src/features/record/hooks/exercise/usePostExercise.ts
  src/hooks/healthKit/index.ts
  src/hooks/healthKit/keys.ts
  src/hooks/healthKit/useGetHealthKitAuthStatus.ts
  src/hooks/healthKit/useSaveHealthKitExercise.ts
  src/navigators/RecordNavigator.tsx
  src/screens/record/create/CreateWorkoutInformationScreen.tsx
  src/screens/record/create/CreateWorkoutMemoScreen.tsx
  src/store/client/createRecordSlice.ts
Labels: 🔥 high priority, 💫 feature

#86 ✨ feat: 매칭 생성 API 연동 및 상세 페이지 연동
  src/features/match/components/CreateMatchInformation/CreateMatchInformationItem.tsx
  src/features/match/components/CreateMatchProfile/CreateMatchProfileSection.tsx
  src/features/match/components/CreateMatchProfile/MatchInformationSection.tsx
  src/features/match/components/MatchDetailProfile/MatchDetailMembers.tsx
  src/features/match/components/MatchDetailProfile/MatchDetailProfileSection.tsx
  src/features/match/components/MatchRadio/MatchCreateRadio.tsx
  src/features/match/hooks/field/usePostField.ts
  src/features/match/types/detail.ts
  src/features/match/types/userField.ts
  src/screens/match/create/CreateMatchInformationScreen.tsx
  src/screens/match/create/CreateMatchProfileScreen.tsx
  src/screens/match/detail/MatchDetailProfileScreen.tsx
  src/screens/match/detail/MatchDetailScreen.tsx
Labels: 🔥 high priority, 💫 feature

#87 ✨ feat: 일반 회원가입(유저 개인정보 입력) 구현
  package-lock.json
  package.json
  src/assets/styles/theme.ts
  src/assets/svg/index.ts
  src/components/Textfield/Textfield.tsx
  src/components/Textfield/index.ts
  src/features/auth/components/signup/IdSection.tsx
  src/features/auth/components/signup/MobilePhoneSection/MobilePhoneSection.tsx
  src/features/auth/components/signup/MobilePhoneSection/SendCodeSection.tsx
  src/features/auth/components/signup/MobilePhoneSection/VerifySection.tsx
  src/features/auth/components/signup/MobilePhoneSection/index.ts
  src/features/auth/components/signup/NameSection.tsx
  src/features/auth/components/signup/PasswordSection/PasswordSection.tsx
  src/features/auth/components/signup/PasswordSection/ValidateGraph.tsx
  src/features/auth/components/signup/PasswordSection/index.ts
  src/features/auth/components/signup/WorkoutLevelSection.tsx
  src/features/auth/components/signup/index.ts
  src/features/auth/hooks/auth/index.ts
  src/features/auth/hooks/auth/keys.ts
  src/features/auth/hooks/auth/useGetAuthIdAvailable.ts
  src/features/auth/hooks/auth/usePostSignup.ts
  src/features/auth/hooks/verification/index.ts
  src/features/auth/hooks/verification/usePostSendCode.ts
  src/features/auth/hooks/verification/usePostVerify.ts
  src/hooks/common/index.ts
  src/hooks/common/useInterval.ts
  src/navigators/AppNavigator.tsx
  src/screens/auth/LandingScreen.tsx
  src/screens/auth/SignupScreen.tsx
Labels: 💫 feature

#95 ✨ feat: axios 배열 파라미터 복수키 포맷 변경
  src/lib/axios.ts
Labels: ♻️ refactor, 💫 feature

#90 ✨ feat: 매칭 상세 팀원탭 - 팀원 목록 및 방장 넘기기, 팀원 제거 API 연동
  src/assets/svg/index.ts
  src/features/match/components/MatchDetailMember/MatchExitButton.tsx
  src/features/match/components/MatchDetailMember/MatchMemberList.tsx
  src/features/match/components/MatchDetailMember/MatchMemberListItem.tsx
  src/features/match/components/MatchDetailMember/MatchMemberSettingBottomSheet.tsx
  src/features/match/components/MatchDetailMember/index.tsx
  src/features/match/hooks/field/usePatchChangeLeader.ts
  src/features/match/hooks/fieldEntry/index.ts
  src/features/match/hooks/fieldEntry/keys.ts
  src/features/match/hooks/fieldEntry/useGetFieldEntryTeam.ts
  src/features/match/hooks/fieldEntry/usePostFieldEntryAccept.ts
  src/features/match/hooks/uesrField/index.ts
  src/features/match/hooks/userField/index.ts
  src/features/match/hooks/userField/keys.ts
  src/features/match/hooks/userField/useDeleteUserFieldEject.ts
  src/features/match/hooks/userField/useDeleteUserFieldExit.ts
  src/features/match/hooks/userField/useGetUserFieldList.ts
  src/features/match/types/detail.ts
  src/features/match/types/fieldEntry.ts
  src/features/match/types/index.ts
  src/features/match/types/member.ts
  src/features/match/types/userField.ts
  src/navigators/MatchNavigator.tsx
  src/screens/match/detail/MatchDetailMemberScreen.tsx
  src/screens/match/detail/MatchDetailProfileScreen.tsx
  src/screens/match/detail/MatchDetailScreen.tsx
  src/screens/match/detail/index.ts
  src/screens/match/detail/member/MatchDetailMemberAssignScreen.tsx
  src/screens/match/detail/member/MatchDetailMemberDeleteScreen.tsx
  src/screens/match/detail/member/MatchDetailMemberMoreScreen.tsx
  src/screens/match/detail/member/MatchDetailMemberRequestAcceptScreen.tsx
  src/screens/match/detail/member/MatchDetailMemberScreen.tsx
  src/screens/match/detail/member/index.ts
Labels: 🔥 high priority, 💫 feature

#89 ✨ feat: 일반 회원가입 - 운동레벨 입력 및 API 연동
  src/features/auth/components/signup/IdSection.tsx
  src/features/auth/components/signup/PasswordSection/PasswordSection.tsx
  src/features/auth/components/signup/WorkoutLevelSection.tsx
  src/features/auth/components/signup/WorkoutLevelSection/WorkoutLevelRadioGroup.tsx
  src/features/auth/components/signup/WorkoutLevelSection/WorkoutLevelSection.tsx
  src/features/auth/components/signup/WorkoutLevelSection/index.ts
  src/features/auth/hooks/auth/index.ts
  src/features/auth/hooks/auth/useGetAuthIdAvailable.ts
  src/features/auth/hooks/auth/usePostLogin.ts
  src/features/auth/hooks/auth/usePostSignup.ts
  src/features/auth/hooks/useAuthStorage.ts
  src/lib/asyncStorage.ts
  src/lib/axios.ts
  src/screens/auth/SignupScreen.tsx
Labels: 💫 feature

#102 🔨 refactor: 매칭 리스트 - API 변동에 따른 응답값 수정
  src/features/match/components/MatchFilter/MatchFieldTypeFilterRadio.tsx
  src/features/match/hooks/field/index.ts
  src/features/match/hooks/field/keys.ts
  src/features/match/hooks/field/useGetFieldCount.ts
  src/features/match/hooks/field/useGetInfiniteFieldList.ts
  src/features/match/types/field.ts
  src/navigators/MatchNavigator.tsx
  src/screens/match/list/MatchListScreen.tsx
Labels: ♻️ refactor, 💫 feature

#96 ✨ feat: MY 매칭 - 신청, 진행중, 진행 완료 매칭 목록 API 연동
  src/features/match/components/MyMatch/MyMatchList.tsx
  src/features/match/components/MyMatch/MyMatchListItem.tsx
  src/features/match/components/MyMatch/MyMatchStatusFilter.tsx
  src/features/match/components/MyMatch/index.ts
  src/features/match/components/index.ts
  src/features/match/const/index.ts
  src/features/match/hooks/fieldEntry/index.ts
  src/features/match/hooks/fieldEntry/keys.ts
  src/features/match/hooks/fieldEntry/useGetInfiniteFieldEntry.ts
  src/features/match/hooks/userField/index.ts
  src/features/match/hooks/userField/keys.ts
  src/features/match/hooks/userField/useGetInfiniteUserFieldCompleted.ts
  src/features/match/hooks/userField/useGetUserFieldProgress.ts
  src/features/match/types/field.ts
  src/features/match/types/fieldEntry.ts
  src/features/match/types/index.ts
  src/navigators/MatchNavigator.tsx
  src/screens/match/MatchScreen.tsx
  src/screens/match/MyMatchListTabScreen.tsx
  src/screens/match/my/MyMatchApplicationScreen.tsx
  src/screens/match/my/MyMatchCompleteScreen.tsx
  src/screens/match/my/MyMatchListScreen.tsx
  src/screens/match/my/MyMatchProgressScreen.tsx
  src/screens/match/my/index.ts
Labels: 💫 feature

#104 ✨ feat: HomeScreen 내 MainBanner 추가
  src/assets/images/main-character-image.png
  src/assets/svg/index.ts
  src/features/home/components/MainBanner.tsx
  src/features/home/components/TodayCalorieSection.tsx
  src/features/home/components/index.ts
  src/features/my/hooks/profile/index.ts
  src/features/my/hooks/profile/keys.ts
  src/features/my/hooks/profile/useGetMyProfileDetail.ts
  src/features/my/types/index.ts
  src/features/my/types/profile.ts
  src/screens/home/HomeScreen.tsx
Labels: 🔥 high priority, 💫 feature
