Repository dnd-side-project/dnd-9th-9-frontend, pull requests merged in 2023-11, with the labels that each got.

#126 ✨ feat: 마이페이지 - 프로필 편집 기능 추가
  src/assets/svg/index.ts
  src/components/Line/Line.tsx
  src/components/TopBar/TopBar.tsx
  src/components/TopBar/index.ts
  src/features/my/components/MyInfoPreview.tsx
  src/features/my/components/index.ts
  src/features/my/components/profile/ProfileListItem.tsx
  src/features/my/components/profile/index.ts
  src/features/my/components/profile/modify/ModifyCalorieGoalSection.tsx
  src/features/my/components/profile/modify/ModifyNameSection.tsx
  src/features/my/components/profile/modify/ModifyWeightSection.tsx
  src/features/my/components/profile/modify/index.ts
  src/navigators/BottomTabNavigator.tsx
  src/navigators/MyNavigator.tsx
  src/screens/my/MyScreen.tsx
  src/screens/my/index.ts
  src/screens/my/profile/MyProfileModifyScreen.tsx
  src/screens/my/profile/MyProfileScreen.tsx
  src/screens/my/profile/index.ts
Labels: 💫 feature

#131 ✨ feat: SplashScreen 추가 및 적용
  ios/HealthMatchingProject/AppDelegate.mm
  ios/HealthMatchingProject/Images.xcassets/Contents.json
  ios/HealthMatchingProject/Images.xcassets/Image.imageset/Contents.json
  ios/HealthMatchingProject/Images.xcassets/Image.imageset/logo@x1.png
  ios/HealthMatchingProject/Images.xcassets/Image.imageset/logo@x2.png
  ios/HealthMatchingProject/Images.xcassets/Image.imageset/logo@x3.png
  ios/HealthMatchingProject/LaunchScreen.storyboard
  ios/Podfile.lock
  package-lock.json
  package.json
  src/App.tsx
  src/screens/splash/SplashScreen.tsx
  src/screens/splash/index.ts
  yarn.lock
Labels: 💫 feature, ⚙️ dependency

#135 🔨 refactor: toast 커스텀 라이브러리 적용
  src/features/match/components/MatchDetailMember/MatchExitButton.tsx
  src/screens/match/detail/matching/MatchDetailMatchingMoreScreen.tsx
  src/screens/match/detail/member/MatchDetailMemberAssignScreen.tsx
  src/screens/match/detail/member/MatchDetailMemberDeleteScreen.tsx
  src/screens/match/detail/member/MatchDetailMemberRequestAcceptScreen.tsx
  src/screens/match/detail/profile/MatchDetailProfileScreen.tsx
  src/screens/match/detail/profile/MatchDetailProfileSettingScreen.tsx
  src/screens/match/detail/profile/UpdateTeamInformationScreen.tsx
  src/screens/match/detail/profile/UpdateTeamProfileScreen.tsx
  src/screens/match/detail/record/MatchDetailRecordScreen.tsx
Labels: ♻️ refactor

#133 ✨ feat: 자동 로그인 및 401 에러 핸들링 기능 추가
  src/features/auth/hooks/auth/index.ts
  src/features/auth/hooks/auth/usePostRefreshAccessToken.ts
  src/lib/axios.ts
  src/navigators/AppNavigator.tsx
  src/screens/auth/LandingScreen.tsx
Labels: 🔥 high priority, 💫 feature

#129 ✨ feat: 마이페이지 - 연결된 계정 및 로그아웃 기능 추가
  src/assets/svg/index.ts
  src/components/Button/Button.tsx
  src/components/CheckBox/LinedCheckBox.tsx
  src/components/CheckBox/index.ts
  src/components/Line/Line.tsx
  src/features/auth/hooks/auth/keys.ts
  src/features/auth/hooks/auth/useGetLogout.ts
  src/features/my/components/index.ts
  src/features/my/components/profile/modify/ModifyCalorieGoalSection.tsx
  src/features/my/components/setting/ConnectedAccount.tsx
  src/features/my/components/setting/ResignationAchievementCard.tsx
  src/features/my/components/setting/index.ts
  src/features/my/const/index.ts
  src/features/my/types/profile.ts
  src/navigators/MyNavigator.tsx
  src/screens/my/MyScreen.tsx
  src/screens/my/setting/SettingConnectedAccount.tsx
  src/screens/my/setting/SettingResignationScreen.tsx
  src/screens/my/setting/SettingScreen.tsx
  src/screens/my/setting/index.ts
Labels: 💫 feature

#143 ✨ feat: app icon 추가
  ios/HealthMatchingProject/Images.xcassets/AppIcon.appiconset/1024px.png
  ios/HealthMatchingProject/Images.xcassets/AppIcon.appiconset/120px 1.png
  ios/HealthMatchingProject/Images.xcassets/AppIcon.appiconset/120px.png
  ios/HealthMatchingProject/Images.xcassets/AppIcon.appiconset/180px.png
  ios/HealthMatchingProject/Images.xcassets/AppIcon.appiconset/40px.png
  ios/HealthMatchingProject/Images.xcassets/AppIcon.appiconset/58px.png
  ios/HealthMatchingProject/Images.xcassets/AppIcon.appiconset/60px.png
  ios/HealthMatchingProject/Images.xcassets/AppIcon.appiconset/80px.png
  ios/HealthMatchingProject/Images.xcassets/AppIcon.appiconset/87px.png
  ios/HealthMatchingProject/Images.xcassets/AppIcon.appiconset/Contents.json
Labels: 🔥 high priority, 💫 feature

#132 ✨ feat: 매칭 상세 - 결과 조회 및 팀 워크 평가
  ios/Podfile.lock
  src/assets/svg/index.ts
  src/components/Tab/DynamicTab.tsx
  src/components/Tab/Tab.tsx
  src/components/Tab/TabContent.tsx
  src/components/Tab/TopTabNavigator.tsx
  src/components/Tab/index.ts
  src/features/match/components/MatchDetailResult/MatchDetailRateSection.tsx
  src/features/match/components/MatchDetailResult/MatchDetailResultAnalyzeTab.tsx
  src/features/match/components/MatchDetailResult/MatchDetailResultAnalyzeTabItem.tsx
  src/features/match/components/MatchDetailResult/MatchDetailResultCard.tsx
  src/features/match/components/MatchDetailResult/MatchDetailResultProfileSection.tsx
  src/features/match/components/MatchDetailResult/MatchDetailResultRateCard.tsx
  src/features/match/components/MatchDetailResult/MatchDetailResultSection.tsx
  src/features/match/components/MatchDetailResult/index.ts
  src/features/match/components/index.ts
  src/features/match/hooks/field/index.ts
  src/features/match/hooks/field/keys.ts
  src/features/match/hooks/field/useGetFieldDetailResult.ts
  src/features/match/hooks/teamworkRate/index.ts
  src/features/match/hooks/teamworkRate/keys.ts
  src/features/match/hooks/teamworkRate/useGetTeamworkIsRatingDone.ts
  src/features/match/hooks/teamworkRate/usePostTeamworkRate.ts
  src/features/match/types/field.ts
  src/screens/match/MatchScreen.tsx
  src/screens/match/detail/MatchDetailScreen.tsx
  src/screens/match/detail/result/MatchDetailResultScreen.tsx
  src/screens/match/detail/result/index.ts
  src/screens/record/RecordsScreen.tsx
  yarn.lock
Labels: 💫 feature

#142 ✨ feat: 고객센터 이메일 발송 연동 기능 추가
  package-lock.json
  package.json
  src/assets/svg/index.ts
  src/screens/my/setting/SettingScreen.tsx
  yarn.lock
Labels: 💫 feature, ⚙️ dependency

#149 ✨ feat: Stack Navigator Header 커스텀 작업
  src/components/Header/HeaderBackButton.tsx
  src/components/Header/HeaderTitle.tsx
  src/components/Header/index.ts
  src/navigators/MatchNavigator.tsx
Labels: ♻️ refactor, 💫 feature

#152 🐛 fix: useGetNotificationUser api 수정
  src/features/notification/hooks/useGetNotificationUser.ts
Labels: 🐛 bug

#150 ✨ feat: 매칭 상세 - 매칭 알림 스크린 작업 및 API 연동
  src/components/Alarm/AlarmItem.tsx
  src/components/Alarm/index.ts
  src/features/match/hooks/notification/index.ts
  src/features/match/hooks/notification/keys.ts
  src/features/match/hooks/notification/useGetInfiniteNotificationField.ts
  src/features/match/hooks/notification/usePatchNotificationRead.ts
  src/features/notification/components/NotificationList.tsx
  src/navigators/MatchNavigator.tsx
  src/screens/match/detail/index.ts
  src/screens/match/detail/notification/MatchDetailNotificationScreen.tsx
  src/screens/match/detail/notification/index.ts
Labels: 💫 feature
