Repository dnd-side-project/dnd-9th-9-frontend, pull requests merged in 2023-08, with the labels that each got.

#10 ✨ feat: Zustand useStore hook 셋팅
  package-lock.json
  package.json
  src/components/Button/Button.tsx
  src/screens/auth/LandingScreen.tsx
  src/store/client/createAuthSlice.ts
  src/store/client/createCounterSlice.ts
  src/store/client/useStore.ts
Labels: 💫 feature, ⚙️ dependency

#14 📝 chore: react-native-health 패키지 및 lib 코드 추가
  ios/HealthMatchingProject.xcodeproj/project.pbxproj
  ios/HealthMatchingProject/AppDelegate.mm
  ios/HealthMatchingProject/HealthMatchingProject.entitlements
  ios/HealthMatchingProject/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
  src/App.tsx
  src/lib/AppleHealthKit.ts
  src/screens/auth/LandingScreen.tsx
  src/screens/record/RecordsTabScreen.tsx
Labels: ⚙️ dependency

#17 📝 chore: async-storage 버전 업데이트 및 예시 코드 추가
  package-lock.json
  package.json
  src/features/auth/hooks/index.ts
  src/features/auth/hooks/useAuthStorage.ts
  src/lib/asyncStorage.ts
  src/utils/types.ts
Labels: ⚙️ dependency

#35 ✨ feat: ListItem 컴포넌트 및 Icon, Tag, Gap 컴포넌트 생성
  ios/HealthMatchingProject.xcodeproj/project.pbxproj
  ios/Podfile.lock
  package-lock.json
  package.json
  src/assets/styles/option.ts
  src/assets/svg/index.ts
  src/components/Button/Button.stories.tsx
  src/components/Gap/Gap.tsx
  src/components/Gap/index.ts
  src/components/Icon/Icon.tsx
  src/components/Icon/index.ts
  src/components/List/ListItem.tsx
  src/components/List/index.ts
  src/components/Tag/Tag.tsx
  src/components/Tag/index.ts
  src/components/Text/Text.stories.tsx
  src/components/Text/Text.tsx
Labels: 💫 feature

#38 🐛 fix: Flatlist error 방지를 위한 미사용 babel plugin 제거
  babel.config.js
Labels: 🐛 bug

#39 ✨ feat: TopTabNavigator 컴포넌트 추가 및 적용
  src/assets/styles/emotion.d.ts
  src/components/TopTabNavigator/TopTabNavigator.tsx
  src/components/TopTabNavigator/index.ts
  src/screens/match/MatchScreen.tsx
  src/screens/record/RecordsScreen.tsx
Labels: 💫 feature

#40 ✨ feat: Modal, ConfirmModal 컴포넌트 추가
  src/components/Modal/ConfirmModal.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/index.ts
  src/components/Text/Text.tsx
  src/screens/auth/LandingScreen.tsx
Labels: 💫 feature

#46 ✨ feat: Searching 컴포넌트 추가
  src/assets/svg/index.ts
  src/components/Searching/Searching.tsx
  src/components/Searching/index.ts
Labels: 💫 feature

#47 ✨ feat: RankingItem, Ranking 컴포넌트 추가
  src/components/Ranking/Ranking.tsx
  src/components/Ranking/RankingItem.tsx
  src/components/Ranking/index.ts
Labels: 💫 feature

#48 ✨ feat: WeeklyCalendar 컴포넌트 추가
  package-lock.json
  package.json
  src/components/Text/Text.tsx
  src/components/WeeklyCalendar/WeeklyCalendar.tsx
  src/components/WeeklyCalendar/index.ts
  src/lib/dayjs.ts
  src/screens/auth/LandingScreen.tsx
Labels: 💫 feature, ⚙️ dependency

#49 ✨ feat: NavigateButton, FilterButton 컴포넌트 추가
  src/assets/svg/index.ts
  src/components/Button/FilterButton.tsx
  src/components/Button/NavigateButton.tsx
  src/components/Button/index.ts
Labels: 💫 feature

#50 ✨ feat: RecordsTabScreen UI 적용 및 임시 데이터 연결
  src/assets/svg/index.ts
  src/features/record/components/WorkoutCard/WorkoutCardGroup.tsx
  src/features/record/components/WorkoutCard/WorkoutCardItem.tsx
  src/features/record/components/WorkoutCard/index.ts
  src/features/record/components/index.ts
  src/lib/AppleHealthKit/AppleHealthKit.ts
  src/lib/AppleHealthKit/const.ts
  src/lib/AppleHealthKit/index.ts
  src/lib/AppleHealthKit/types.ts
  src/screens/record/RecordsTabScreen.tsx
Labels: 💫 feature

#52 ✨ feat: AlarmItem 컴포넌트 추가
  src/components/Alarm/AlarmItem.tsx
  src/components/Alarm/index.ts
  src/screens/auth/LandingScreen.tsx
  src/utils/regex.ts
Labels: 💫 feature

#51 ✨ feat: MatchList 관련 화면 플로우 연동
  src/assets/svg/index.ts
  src/components/List/ListItem.tsx
  src/features/match/components/MatchList/MatchingList.tsx
  src/features/match/components/MatchList/index.ts
  src/features/match/components/MatchingFloating/AddMatchingButton.tsx
  src/features/match/components/MatchingFloating/AutoMatchingButton.tsx
  src/features/match/components/MatchingFloating/CloseMatchingButton.tsx
  src/features/match/components/MatchingFloating/MatchingFloating.tsx
  src/features/match/components/MatchingFloating/index.ts
  src/features/match/components/MatchingRadio/MatchingTypeRadio.tsx
  src/features/match/components/MatchingRadio/index.ts
  src/features/match/components/index.ts
  src/navigators/BottomTabNavigator.tsx
  src/navigators/MatchNavigator.tsx
  src/navigators/index.ts
  src/screens/match/MatchScreen.tsx
  src/screens/match/TotalMatchListTabScreen.tsx
  src/screens/match/create/CreateTeamProfileScreen.tsx
  src/screens/match/create/CreateTeamScreen.tsx
  src/screens/match/create/index.ts
  src/screens/match/detail/MatchDetailScreen.tsx
  src/screens/match/detail/index.ts
  src/screens/match/list/AutoMatchScreen.tsx
  src/screens/match/list/MatchFilterScreen.tsx
  src/screens/match/list/MatchListScreen.tsx
  src/screens/match/list/index.ts
Labels: 🔥 high priority, 💫 feature

#54 📝 chore: eslint 및 husky 설정 추가
  .eslintrc.js
  .eslintrc.json
  .husky/pre-commit
  package-lock.json
  package.json
  src/App.tsx
  src/components/Alarm/AlarmItem.tsx
  src/components/Button/Button.tsx
  src/components/Button/FilterButton.tsx
  src/components/Button/NavigateButton.tsx
  src/components/Gap/Gap.tsx
  src/components/Icon/Icon.tsx
  src/components/List/ListItem.tsx
  src/components/Modal/ConfirmModal.tsx
  src/components/Modal/Modal.tsx
  src/components/Ranking/Ranking.tsx
  src/components/Ranking/RankingItem.tsx
  src/components/Searching/Searching.tsx
  src/components/Tag/Tag.tsx
  src/components/Text/Text.tsx
  src/components/TopTabNavigator/TopTabNavigator.tsx
  src/components/WeeklyCalendar/WeeklyCalendar.tsx
  src/features/auth/hooks/useAuthStorage.ts
  src/features/match/components/MatchList/MatchingList.tsx
  src/features/match/components/MatchingFloating/AddMatchingButton.tsx
  src/features/match/components/MatchingFloating/AutoMatchingButton.tsx
  src/features/match/components/MatchingFloating/CloseMatchingButton.tsx
  src/features/match/components/MatchingFloating/MatchingFloating.tsx
  src/features/match/components/MatchingRadio/MatchingTypeRadio.tsx
  src/features/record/components/WorkoutCard/WorkoutCardGroup.tsx
  src/features/record/components/WorkoutCard/WorkoutCardItem.tsx
  src/lib/AppleHealthKit/AppleHealthKit.ts
  src/lib/AppleHealthKit/types.ts
  src/lib/asyncStorage.ts
  src/lib/dayjs.ts
  src/navigators/AppNavigator.tsx
  src/navigators/BottomTabNavigator.tsx
  src/navigators/MatchNavigator.tsx
  src/screens/auth/LandingScreen.tsx
  src/screens/auth/LoginScreen.tsx
  src/screens/auth/SignupScreen.tsx
  src/screens/home/HomeScreen.tsx
  src/screens/match/MatchScreen.tsx
  src/screens/match/MyMatchListTabScreen.tsx
  src/screens/match/create/CreateTeamProfileScreen.tsx
  src/screens/match/create/CreateTeamScreen.tsx
  src/screens/match/detail/MatchDetailScreen.tsx
  src/screens/match/list/AutoMatchScreen.tsx
  src/screens/match/list/MatchFilterScreen.tsx
  src/screens/match/list/MatchListScreen.tsx
  src/screens/my/MyScreen.tsx
  src/screens/record/RecordsScreen.tsx
  src/screens/record/RecordsTabScreen.tsx
  src/screens/record/SummaryTabScreen.tsx
  src/store/client/createAuthSlice.ts
  src/store/client/createCounterSlice.ts
  src/store/client/useStore.ts
  src/utils/regex.ts
Labels: ⚙️ dependency

#57 📝 chore: axios, react-query 패키지 및 기본 코드 추가
  package-lock.json
  package.json
  src/App.tsx
  src/features/match/hooks/field/index.ts
  src/features/match/hooks/field/keys.ts
  src/features/match/hooks/field/useGetAutoField.ts
  src/features/match/hooks/field/useGetFieldDetail.ts
  src/features/match/hooks/field/useGetFieldList.ts
  src/features/match/hooks/field/usePostField.ts
  src/features/match/hooks/uesrField/index.ts
  src/features/match/hooks/uesrField/keys.ts
  src/features/match/hooks/uesrField/useGetUserFieldList.ts
  src/features/match/types/field.ts
  src/features/match/types/index.ts
  src/features/match/types/userField.ts
  src/features/record/hooks/bookmark/index.ts
  src/features/record/hooks/bookmark/keys.ts
  src/features/record/hooks/bookmark/useGetBookmarkList.ts
  src/features/record/hooks/bookmark/usePostBookmark.ts
  src/features/record/hooks/exercise/index.ts
  src/features/record/hooks/exercise/keys.ts
  src/features/record/hooks/exercise/useGetExerciseCalorie.ts
  src/features/record/hooks/exercise/useGetExerciseList.ts
  src/features/record/hooks/exercise/useGetExerciseSummary.ts
  src/features/record/hooks/exercise/useGetRecentExercise.ts
  src/features/record/hooks/exercise/usePostAppleExercise.ts
  src/features/record/hooks/exercise/usePostExercise.ts
  src/features/record/types/bookmark.ts
  src/features/record/types/exercise.ts
  src/features/record/types/index.ts
  src/lib/axios.ts
  src/lib/react-query.ts
Labels: 💫 feature

#55 ✨ feat: MatchDetailProfileScreen UI 작업 및 더미 데이터 연동
  package-lock.json
  package.json
  src/components/Line/Line.tsx
  src/components/Line/index.ts
  src/components/List/ListItem.tsx
  src/features/match/components/MatchDetailProfile/MatchDetailMembers.tsx
  src/features/match/components/MatchDetailProfile/MatchDetailProfileSection.tsx
  src/features/match/components/MatchDetailProfile/index.ts
  src/features/match/const/index.ts
  src/features/match/hooks/index.ts
  src/features/match/types/detail.ts
  src/features/match/types/field.ts
  src/features/match/types/index.ts
  src/features/match/types/member.ts
  src/navigators/MatchNavigator.tsx
  src/screens/match/detail/MatchDetailMatchingScreen.tsx
  src/screens/match/detail/MatchDetailMemberScreen.tsx
  src/screens/match/detail/MatchDetailProfileScreen.tsx
  src/screens/match/detail/MatchDetailRecordScreen.tsx
  src/screens/match/detail/MatchDetailScreen.tsx
  src/screens/match/detail/index.ts
  src/screens/match/index.ts
Labels: 🔥 high priority, 💫 feature

#60 ✨ feat: bottom tab 스타일 추가
  src/assets/svg/index.ts
  src/components/Icon/Icon.tsx
  src/navigators/BottomTabNavigator.tsx
Labels: 💫 feature

#63 ✨ feat: 운동 요약 스크린 추가
  src/components/WeeklyCalendar/WeeklyCalendar.tsx
  src/features/record/components/SummaryCard/SummaryCardGroup.tsx
  src/features/record/components/SummaryCard/SummaryCardItem.tsx
  src/features/record/components/SummaryCard/index.ts
  src/screens/record/RecordsTabScreen.tsx
  src/screens/record/SummaryTabScreen.tsx
  src/store/client/createRecordSlice.ts
  src/store/client/useStore.ts
Labels: 💫 feature

#62 ✨ feat: 매칭 생성 정보, 프로필 UI 및 더미 데이터 연동
  ios/Podfile.lock
  package-lock.json
  package.json
  src/assets/svg/index.ts
  src/components/Count/Count.tsx
  src/components/Count/index.ts
  src/features/match/components/CreateMatchInformation/CreateMatchInformationItem.tsx
  src/features/match/components/CreateMatchInformation/index.ts
  src/features/match/components/CreateMatchProfile/CreateMatchProfileSection.tsx
  src/features/match/components/CreateMatchProfile/MatchInformationSection.tsx
  src/features/match/components/CreateMatchProfile/index.ts
  src/features/match/components/MatchRadio/MatchCreateRadio.tsx
  src/features/match/components/MatchRadio/MatchTypeRadio.tsx
  src/features/match/components/MatchRadio/index.ts
  src/features/match/components/MatchingRadio/index.ts
  src/features/match/components/index.ts
  src/features/match/hooks/field/usePostField.ts
  src/features/match/types/field.ts
  src/navigators/MatchNavigator.tsx
  src/screens/match/create/CreateMatchInformationScreen.tsx
  src/screens/match/create/CreateMatchProfileScreen.tsx
  src/screens/match/create/CreateTeamProfileScreen.tsx
  src/screens/match/create/CreateTeamScreen.tsx
  src/screens/match/create/index.ts
  src/screens/match/list/MatchListScreen.tsx
  src/store/client/createMatchSlice.ts
  src/store/client/useStore.ts
Labels: 🔥 high priority, 💫 feature

#64 ✨ feat: 매칭 상세 매칭 탭 스크린 및 더미 데이터 연동
  src/assets/svg/index.ts
  src/components/CheckBox/CheckBox.tsx
  src/components/CheckBox/index.ts
  src/features/match/components/MatchDetailMatching/MatchApplyList.tsx
  src/features/match/components/MatchDetailMatching/MatchApplyListItem.tsx
  src/features/match/components/MatchDetailMatching/index.ts
  src/features/match/hooks/field/keys.ts
  src/features/match/hooks/field/useGetFieldDetailEntryBattle.ts
  src/features/match/hooks/index.ts
  src/features/match/types/detail.ts
  src/navigators/MatchNavigator.tsx
  src/screens/match/detail/MatchDetailMatchingScreen.tsx
  src/screens/match/detail/MatchDetailScreen.tsx
  src/screens/match/detail/index.ts
  src/screens/match/detail/matching/MatchDetailMatchingMoreScreen.tsx
  src/screens/match/detail/matching/MatchDetailMatchingScreen.tsx
  src/screens/match/detail/matching/index.ts
  src/store/client/createMatchDetailSlice.ts
Labels: 🔥 high priority, 💫 feature

#67 ✨ feat: 매칭 상세 기록탭 스크린, 매칭 상세 기록 상세 스크린 UI 및 더미 데이터 셋팅
  src/assets/svg/index.ts
  src/components/Button/NavigateButton.tsx
  src/components/Carousel/Carousel.tsx
  src/components/Carousel/index.ts
  src/components/Text/Text.tsx
  src/components/TopTabNavigator/TopTabNavigator.tsx
  src/features/match/components/MatchDetailRecord/MatchDetailRecordCard.tsx
  src/features/match/components/MatchDetailRecord/MatchDetailRecordCardItem.tsx
  src/features/match/components/MatchDetailRecord/MatchDetailRecordCarousel.tsx
  src/features/match/components/MatchDetailRecord/RecordDetailInformationItem.tsx
  src/features/match/components/MatchDetailRecord/index.ts
  src/features/match/components/MatchList/MatchingList.tsx
  src/features/match/hooks/field/keys.ts
  src/features/match/hooks/field/useGetFieldRecord.ts
  src/features/match/types/detail.ts
  src/lib/AppleHealthKit/const.ts
  src/lib/AppleHealthKit/types.ts
  src/navigators/MatchNavigator.tsx
  src/screens/match/detail/MatchDetailProfileScreen.tsx
  src/screens/match/detail/MatchDetailRecordScreen.tsx
  src/screens/match/detail/MatchDetailScreen.tsx
  src/screens/match/detail/index.ts
  src/screens/match/detail/record/MatchDetailRecordDetailScreen.tsx
  src/screens/match/detail/record/MatchDetailRecordScreen.tsx
  src/screens/match/detail/record/index.ts
  src/screens/match/list/MatchListScreen.tsx
Labels: 🔥 high priority, 💫 feature

#70 ✨ feat: query placeholderData를 initialData로 변경
  src/features/match/hooks/field/keys.ts
  src/features/match/hooks/field/useGetAutoField.ts
  src/features/match/hooks/field/useGetFieldDetail.ts
  src/features/match/hooks/field/useGetFieldList.ts
  src/features/record/hooks/bookmark/useGetBookmarkList.ts
  src/features/record/hooks/exercise/useGetExerciseCalorie.ts
  src/features/record/hooks/exercise/useGetExerciseList.ts
  src/features/record/hooks/exercise/useGetExerciseSummary.ts
  src/features/record/hooks/exercise/useGetRecentExercise.ts
Labels: 💫 feature

#72 🐛 fix: 매칭 상세 매칭탭 프로필 navigate 이슈 해결
  src/navigators/MatchNavigator.tsx
  src/screens/match/detail/MatchDetailProfileScreen.tsx
  src/screens/match/detail/matching/MatchDetailMatchingMoreScreen.tsx
  src/screens/match/detail/matching/MatchDetailMatchingScreen.tsx
Labels: 🐛 bug

#73 ✨ feat: 운동 종류, 시간 입력 기능 추가
  src/components/BottomSheet/BottomSheet.tsx
  src/features/record/components/CreateWorkoutInformation/Modal/WorkoutActivityTimeModal.tsx
  src/features/record/components/CreateWorkoutInformation/Modal/WorkoutActivityTypeModal.tsx
  src/features/record/components/CreateWorkoutInformation/Modal/index.ts
  src/lib/AppleHealthKit/AppleHealthKit.ts
  src/lib/AppleHealthKit/const.ts
  src/navigators/BottomTabNavigator.tsx
  src/navigators/RecordNavigator.tsx
  src/screens/auth/LandingScreen.tsx
  src/screens/record/RecordsScreen.tsx
  src/screens/record/create/CreateWorkoutInformationScreen.tsx
  src/screens/record/create/CreateWorkoutMemoScreen.tsx
  src/screens/record/create/index.ts
  src/store/client/createRecordSlice.ts
  src/utils/types.ts
Labels: 💫 feature
