Repository dnd-side-project/dnd-9th-9-frontend, pull requests merged in 2023-12, with the labels that each got.

#147 ✨ feat: 마이페이지 - 나의 불꽃 레벨 카드, 설명 스크린 추가
  src/assets/styles/theme.ts
  src/assets/svg/index.ts
  src/features/my/components/index.ts
  src/features/my/components/overview/MyInfoPreview.tsx
  src/features/my/components/overview/TeamworkRateSection/TeamworkRateFlameGroup.tsx
  src/features/my/components/overview/TeamworkRateSection/TeamworkRateSection.tsx
  src/features/my/components/overview/TeamworkRateSection/index.ts
  src/features/my/components/overview/index.ts
  src/features/my/const/index.ts
  src/navigators/MyNavigator.tsx
  src/screens/my/MyScreen.tsx
  src/screens/my/TeamWorkRateInfo.tsx
  src/screens/my/index.ts
Labels: 💫 feature

#153 🐛 fix: useGetFieldEntryTeam 데이터 노출 이슈 해결
  src/features/match/components/MatchDetailMember/MatchMemberList.tsx
  src/screens/match/detail/member/MatchDetailMemberMoreScreen.tsx
  src/screens/match/detail/member/MatchDetailMemberRequestAcceptScreen.tsx
Labels: 🐛 bug

#154 🐛 fix: TeamWorkRateInfo(불꽃 레벨 설명 스크린) TopBar 사용으로 변경
  src/components/TopBar/TopBar.tsx
  src/navigators/MyNavigator.tsx
  src/screens/my/TeamWorkRateInfo.tsx
  src/screens/my/profile/MyProfileModifyScreen.tsx
  src/screens/my/profile/MyProfileScreen.tsx
  src/screens/my/setting/SettingConnectedAccount.tsx
  src/screens/my/setting/SettingResignationScreen.tsx
  src/screens/my/setting/SettingScreen.tsx
Labels: 🐛 bug, ♻️ refactor

#156 🐛 fix: handle401Error 조건문 수정
  src/lib/axios.ts
Labels: 🐛 bug

#157 📝 chore: axios api url을 .env 참조하도록 수정
  .gitignore
  babel.config.js
  package-lock.json
  package.json
  src/lib/axios.ts
  src/types/env.d.ts
Labels: ⚙️ dependency

#158 📝 chore: Testflight 심사 통과를 위해 추가 및 수정 데이터 업데이트
  ios/HealthMatchingProject.xcodeproj/project.pbxproj
  ios/HealthMatchingProject/Info.plist
Labels: 🗃 infra

#159 🔨 refactor: NotificationList 공용 컴포넌트 FlatList 사용하도록 리팩토링
  src/features/notification/components/NotificationList.tsx
Labels: ♻️ refactor
